// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/custom-fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/custom-fields">> = Specific
  const handler = {} as typeof import("../../../app/admin/custom-fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/departments">> = Specific
  const handler = {} as typeof import("../../../app/admin/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees">> = Specific
  const handler = {} as typeof import("../../../app/admin/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/feature-flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feature-flags">> = Specific
  const handler = {} as typeof import("../../../app/admin/feature-flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/holidays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/holidays">> = Specific
  const handler = {} as typeof import("../../../app/admin/holidays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/implicit-roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/implicit-roles">> = Specific
  const handler = {} as typeof import("../../../app/admin/implicit-roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/import-keka/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/import-keka">> = Specific
  const handler = {} as typeof import("../../../app/admin/import-keka/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../../app/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leave-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leave-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/leave-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leave-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leave-types">> = Specific
  const handler = {} as typeof import("../../../app/admin/leave-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/mobile-api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mobile-api">> = Specific
  const handler = {} as typeof import("../../../app/admin/mobile-api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/office-locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/office-locations">> = Specific
  const handler = {} as typeof import("../../../app/admin/office-locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/org-hierarchy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/org-hierarchy">> = Specific
  const handler = {} as typeof import("../../../app/admin/org-hierarchy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payroll">> = Specific
  const handler = {} as typeof import("../../../app/admin/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/permissions">> = Specific
  const handler = {} as typeof import("../../../app/admin/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../../app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../../app/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shifts">> = Specific
  const handler = {} as typeof import("../../../app/admin/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system">> = Specific
  const handler = {} as typeof import("../../../app/admin/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/allocations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/allocations">> = Specific
  const handler = {} as typeof import("../../../app/allocations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/allocations/summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/allocations/summary">> = Specific
  const handler = {} as typeof import("../../../app/allocations/summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/org-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/org-health">> = Specific
  const handler = {} as typeof import("../../../app/analytics/org-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../../app/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/fluence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/fluence">> = Specific
  const handler = {} as typeof import("../../../app/app/fluence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/grow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/grow">> = Specific
  const handler = {} as typeof import("../../../app/app/grow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/hire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/hire">> = Specific
  const handler = {} as typeof import("../../../app/app/hire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/hrms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/hrms">> = Specific
  const handler = {} as typeof import("../../../app/app/hrms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/approvals/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals/inbox">> = Specific
  const handler = {} as typeof import("../../../app/approvals/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals">> = Specific
  const handler = {} as typeof import("../../../app/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../../app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/comp-off/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance/comp-off">> = Specific
  const handler = {} as typeof import("../../../app/attendance/comp-off/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/my-attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance/my-attendance">> = Specific
  const handler = {} as typeof import("../../../app/attendance/my-attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../../app/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/regularization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance/regularization">> = Specific
  const handler = {} as typeof import("../../../app/attendance/regularization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/shift-swap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance/shift-swap">> = Specific
  const handler = {} as typeof import("../../../app/attendance/shift-swap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance/team">> = Specific
  const handler = {} as typeof import("../../../app/attendance/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/benefits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benefits">> = Specific
  const handler = {} as typeof import("../../../app/benefits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/biometric-devices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biometric-devices">> = Specific
  const handler = {} as typeof import("../../../app/biometric-devices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/calendar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/[id]">> = Specific
  const handler = {} as typeof import("../../../app/calendar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/calendar/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/new">> = Specific
  const handler = {} as typeof import("../../../app/calendar/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/company-spotlight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company-spotlight">> = Specific
  const handler = {} as typeof import("../../../app/company-spotlight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compensation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compensation">> = Specific
  const handler = {} as typeof import("../../../app/compensation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../../app/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contracts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/contracts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contracts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/new">> = Specific
  const handler = {} as typeof import("../../../app/contracts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts">> = Specific
  const handler = {} as typeof import("../../../app/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contracts/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts/templates">> = Specific
  const handler = {} as typeof import("../../../app/contracts/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboards/employee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboards/employee">> = Specific
  const handler = {} as typeof import("../../../app/dashboards/employee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboards/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboards/executive">> = Specific
  const handler = {} as typeof import("../../../app/dashboards/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboards/manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboards/manager">> = Specific
  const handler = {} as typeof import("../../../app/dashboards/manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/departments">> = Specific
  const handler = {} as typeof import("../../../app/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/[id]/compensation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/compensation">> = Specific
  const handler = {} as typeof import("../../../app/employees/[id]/compensation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/employees/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]">> = Specific
  const handler = {} as typeof import("../../../app/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/change-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/change-requests">> = Specific
  const handler = {} as typeof import("../../../app/employees/change-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/directory">> = Specific
  const handler = {} as typeof import("../../../app/employees/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/import">> = Specific
  const handler = {} as typeof import("../../../app/employees/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../../app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executive">> = Specific
  const handler = {} as typeof import("../../../app/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/exit-interview/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exit-interview/[token]">> = Specific
  const handler = {} as typeof import("../../../app/exit-interview/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/expenses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/approvals">> = Specific
  const handler = {} as typeof import("../../../app/expenses/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/mileage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/mileage">> = Specific
  const handler = {} as typeof import("../../../app/expenses/mileage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../../app/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/reports">> = Specific
  const handler = {} as typeof import("../../../app/expenses/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/expenses/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/settings">> = Specific
  const handler = {} as typeof import("../../../app/expenses/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../../app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/feedback360/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback360">> = Specific
  const handler = {} as typeof import("../../../app/feedback360/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/analytics">> = Specific
  const handler = {} as typeof import("../../../app/fluence/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/blogs/[slug]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/blogs/[slug]/edit">> = Specific
  const handler = {} as typeof import("../../../app/fluence/blogs/[slug]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/fluence/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/blogs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/blogs/new">> = Specific
  const handler = {} as typeof import("../../../app/fluence/blogs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/blogs">> = Specific
  const handler = {} as typeof import("../../../app/fluence/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/fluence/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/drive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/drive">> = Specific
  const handler = {} as typeof import("../../../app/fluence/drive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/my-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/my-content">> = Specific
  const handler = {} as typeof import("../../../app/fluence/my-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence">> = Specific
  const handler = {} as typeof import("../../../app/fluence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/search">> = Specific
  const handler = {} as typeof import("../../../app/fluence/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/templates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/templates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/fluence/templates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/templates/new">> = Specific
  const handler = {} as typeof import("../../../app/fluence/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/templates">> = Specific
  const handler = {} as typeof import("../../../app/fluence/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/wall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/wall">> = Specific
  const handler = {} as typeof import("../../../app/fluence/wall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/wiki/[slug]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/wiki/[slug]/edit">> = Specific
  const handler = {} as typeof import("../../../app/fluence/wiki/[slug]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/wiki/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/wiki/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/fluence/wiki/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/wiki/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/wiki/new">> = Specific
  const handler = {} as typeof import("../../../app/fluence/wiki/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fluence/wiki/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fluence/wiki">> = Specific
  const handler = {} as typeof import("../../../app/fluence/wiki/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../../app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/helpdesk/knowledge-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/knowledge-base">> = Specific
  const handler = {} as typeof import("../../../app/helpdesk/knowledge-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/helpdesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk">> = Specific
  const handler = {} as typeof import("../../../app/helpdesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/helpdesk/sla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/sla">> = Specific
  const handler = {} as typeof import("../../../app/helpdesk/sla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/helpdesk/tickets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../../app/helpdesk/tickets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/helpdesk/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/tickets">> = Specific
  const handler = {} as typeof import("../../../app/helpdesk/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/holidays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/holidays">> = Specific
  const handler = {} as typeof import("../../../app/holidays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/import-export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import-export">> = Specific
  const handler = {} as typeof import("../../../app/import-export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/integrations/slack/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/slack">> = Specific
  const handler = {} as typeof import("../../../app/integrations/slack/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge">> = Specific
  const handler = {} as typeof import("../../../app/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/certificates">> = Specific
  const handler = {} as typeof import("../../../app/learning/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/courses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/learning/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/courses/[id]/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/courses/[id]/play">> = Specific
  const handler = {} as typeof import("../../../app/learning/courses/[id]/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/courses/[id]/quiz/[quizId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/courses/[id]/quiz/[quizId]">> = Specific
  const handler = {} as typeof import("../../../app/learning/courses/[id]/quiz/[quizId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/courses">> = Specific
  const handler = {} as typeof import("../../../app/learning/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning">> = Specific
  const handler = {} as typeof import("../../../app/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning/paths/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning/paths">> = Specific
  const handler = {} as typeof import("../../../app/learning/paths/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/admin/carry-forward/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/admin/carry-forward">> = Specific
  const handler = {} as typeof import("../../../app/leave/admin/carry-forward/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/apply">> = Specific
  const handler = {} as typeof import("../../../app/leave/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/approvals">> = Specific
  const handler = {} as typeof import("../../../app/leave/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/calendar">> = Specific
  const handler = {} as typeof import("../../../app/leave/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/encashment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/encashment">> = Specific
  const handler = {} as typeof import("../../../app/leave/encashment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/my-leaves/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/my-leaves">> = Specific
  const handler = {} as typeof import("../../../app/leave/my-leaves/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave">> = Specific
  const handler = {} as typeof import("../../../app/leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leave/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leave/team">> = Specific
  const handler = {} as typeof import("../../../app/leave/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/letters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/letters">> = Specific
  const handler = {} as typeof import("../../../app/letters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/letters/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/letters/templates">> = Specific
  const handler = {} as typeof import("../../../app/letters/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/linkedin-posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/linkedin-posts">> = Specific
  const handler = {} as typeof import("../../../app/linkedin-posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/loans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loans/[id]">> = Specific
  const handler = {} as typeof import("../../../app/loans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/loans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loans/new">> = Specific
  const handler = {} as typeof import("../../../app/loans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/loans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loans">> = Specific
  const handler = {} as typeof import("../../../app/loans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/lwf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lwf">> = Specific
  const handler = {} as typeof import("../../../app/lwf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/assets">> = Specific
  const handler = {} as typeof import("../../../app/me/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/attendance">> = Specific
  const handler = {} as typeof import("../../../app/me/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/me/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/documents">> = Specific
  const handler = {} as typeof import("../../../app/me/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/leaves/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/leaves">> = Specific
  const handler = {} as typeof import("../../../app/me/leaves/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/payslips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/payslips">> = Specific
  const handler = {} as typeof import("../../../app/me/payslips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me/profile">> = Specific
  const handler = {} as typeof import("../../../app/me/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nu-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nu-calendar">> = Specific
  const handler = {} as typeof import("../../../app/nu-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nu-drive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nu-drive">> = Specific
  const handler = {} as typeof import("../../../app/nu-drive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nu-mail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nu-mail">> = Specific
  const handler = {} as typeof import("../../../app/nu-mail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/[id]/exit-interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding/[id]/exit-interview">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/[id]/exit-interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/[id]/fnf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding/[id]/fnf">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/[id]/fnf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding/[id]">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/exit/fnf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding/exit/fnf">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/exit/fnf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/fnf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding/fnf">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/fnf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offboarding">> = Specific
  const handler = {} as typeof import("../../../app/offboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offer-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offer-portal">> = Specific
  const handler = {} as typeof import("../../../app/offer-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/okr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/okr">> = Specific
  const handler = {} as typeof import("../../../app/okr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/[id]">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/new">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/templates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/templates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/templates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/templates/new">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/templates">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/one-on-one/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/one-on-one">> = Specific
  const handler = {} as typeof import("../../../app/one-on-one/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/overtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overtime">> = Specific
  const handler = {} as typeof import("../../../app/overtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payments/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/config">> = Specific
  const handler = {} as typeof import("../../../app/payments/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../../app/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/bulk-processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/bulk-processing">> = Specific
  const handler = {} as typeof import("../../../app/payroll/bulk-processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/components">> = Specific
  const handler = {} as typeof import("../../../app/payroll/components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll">> = Specific
  const handler = {} as typeof import("../../../app/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/payslips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/payslips">> = Specific
  const handler = {} as typeof import("../../../app/payroll/payslips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/runs">> = Specific
  const handler = {} as typeof import("../../../app/payroll/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/salary-structures/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/salary-structures/create">> = Specific
  const handler = {} as typeof import("../../../app/payroll/salary-structures/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/salary-structures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/salary-structures">> = Specific
  const handler = {} as typeof import("../../../app/payroll/salary-structures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/statutory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/statutory">> = Specific
  const handler = {} as typeof import("../../../app/payroll/statutory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payroll/structures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/structures">> = Specific
  const handler = {} as typeof import("../../../app/payroll/structures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/360-feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/360-feedback">> = Specific
  const handler = {} as typeof import("../../../app/performance/360-feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/9box/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/9box">> = Specific
  const handler = {} as typeof import("../../../app/performance/9box/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/calibration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/calibration">> = Specific
  const handler = {} as typeof import("../../../app/performance/calibration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/competency-framework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/competency-framework">> = Specific
  const handler = {} as typeof import("../../../app/performance/competency-framework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/competency-matrix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/competency-matrix">> = Specific
  const handler = {} as typeof import("../../../app/performance/competency-matrix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/cycles/[id]/calibration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/cycles/[id]/calibration">> = Specific
  const handler = {} as typeof import("../../../app/performance/cycles/[id]/calibration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/cycles/[id]/nine-box/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/cycles/[id]/nine-box">> = Specific
  const handler = {} as typeof import("../../../app/performance/cycles/[id]/nine-box/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/cycles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/cycles">> = Specific
  const handler = {} as typeof import("../../../app/performance/cycles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/feedback">> = Specific
  const handler = {} as typeof import("../../../app/performance/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/goals">> = Specific
  const handler = {} as typeof import("../../../app/performance/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/okr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/okr">> = Specific
  const handler = {} as typeof import("../../../app/performance/okr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/okrs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/okrs">> = Specific
  const handler = {} as typeof import("../../../app/performance/okrs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../../app/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/pip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/pip">> = Specific
  const handler = {} as typeof import("../../../app/performance/pip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/reviews">> = Specific
  const handler = {} as typeof import("../../../app/performance/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/revolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance/revolution">> = Specific
  const handler = {} as typeof import("../../../app/performance/revolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/preboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preboarding">> = Specific
  const handler = {} as typeof import("../../../app/preboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/preboarding/portal/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preboarding/portal/[token]">> = Specific
  const handler = {} as typeof import("../../../app/preboarding/portal/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/predictive-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predictive-analytics">> = Specific
  const handler = {} as typeof import("../../../app/predictive-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/probation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/probation">> = Specific
  const handler = {} as typeof import("../../../app/probation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/calendar">> = Specific
  const handler = {} as typeof import("../../../app/projects/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/gantt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/gantt">> = Specific
  const handler = {} as typeof import("../../../app/projects/gantt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/resource-conflicts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/resource-conflicts">> = Specific
  const handler = {} as typeof import("../../../app/projects/resource-conflicts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recognition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recognition">> = Specific
  const handler = {} as typeof import("../../../app/recognition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/[jobId]/kanban/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/[jobId]/kanban">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/[jobId]/kanban/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/agencies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/agencies/[id]">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/agencies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/agencies">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/candidates/[id]/offer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/candidates/[id]/offer">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/candidates/[id]/offer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/candidates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/candidates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/candidates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/candidates">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/career-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/career-page">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/career-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/interviews">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/job-boards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/job-boards">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/job-boards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/jobs">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recruitment/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/recruitment/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals">> = Specific
  const handler = {} as typeof import("../../../app/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/attrition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/attrition">> = Specific
  const handler = {} as typeof import("../../../app/reports/attrition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/builder">> = Specific
  const handler = {} as typeof import("../../../app/reports/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/headcount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/headcount">> = Specific
  const handler = {} as typeof import("../../../app/reports/headcount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/leave">> = Specific
  const handler = {} as typeof import("../../../app/reports/leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/payroll">> = Specific
  const handler = {} as typeof import("../../../app/reports/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/performance">> = Specific
  const handler = {} as typeof import("../../../app/reports/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/scheduled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/scheduled">> = Specific
  const handler = {} as typeof import("../../../app/reports/scheduled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/utilization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/utilization">> = Specific
  const handler = {} as typeof import("../../../app/reports/utilization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/approvals">> = Specific
  const handler = {} as typeof import("../../../app/resources/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/availability">> = Specific
  const handler = {} as typeof import("../../../app/resources/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/capacity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/capacity">> = Specific
  const handler = {} as typeof import("../../../app/resources/capacity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../../app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/pool/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/pool">> = Specific
  const handler = {} as typeof import("../../../app/resources/pool/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/workload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/workload">> = Specific
  const handler = {} as typeof import("../../../app/resources/workload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/restricted-holidays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restricted-holidays">> = Specific
  const handler = {} as typeof import("../../../app/restricted-holidays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../../app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/notifications">> = Specific
  const handler = {} as typeof import("../../../app/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../../app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/security">> = Specific
  const handler = {} as typeof import("../../../app/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/sso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/sso">> = Specific
  const handler = {} as typeof import("../../../app/settings/sso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shifts/definitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts/definitions">> = Specific
  const handler = {} as typeof import("../../../app/shifts/definitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shifts/my-schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts/my-schedule">> = Specific
  const handler = {} as typeof import("../../../app/shifts/my-schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts">> = Specific
  const handler = {} as typeof import("../../../app/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shifts/patterns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts/patterns">> = Specific
  const handler = {} as typeof import("../../../app/shifts/patterns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/shifts/swaps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shifts/swaps">> = Specific
  const handler = {} as typeof import("../../../app/shifts/swaps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign/[token]">> = Specific
  const handler = {} as typeof import("../../../app/sign/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/statutory/filings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/statutory/filings">> = Specific
  const handler = {} as typeof import("../../../app/statutory/filings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/statutory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/statutory">> = Specific
  const handler = {} as typeof import("../../../app/statutory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/surveys/[id]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/[id]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/surveys/[id]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/surveys/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/[id]">> = Specific
  const handler = {} as typeof import("../../../app/surveys/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/surveys/[id]/respond/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys/[id]/respond">> = Specific
  const handler = {} as typeof import("../../../app/surveys/[id]/respond/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surveys">> = Specific
  const handler = {} as typeof import("../../../app/surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tax/declarations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax/declarations">> = Specific
  const handler = {} as typeof import("../../../app/tax/declarations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax">> = Specific
  const handler = {} as typeof import("../../../app/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/team-directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team-directory">> = Specific
  const handler = {} as typeof import("../../../app/team-directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/time-tracking/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/time-tracking/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/time-tracking/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/time-tracking/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/time-tracking/[id]">> = Specific
  const handler = {} as typeof import("../../../app/time-tracking/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/time-tracking/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/time-tracking/new">> = Specific
  const handler = {} as typeof import("../../../app/time-tracking/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/time-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/time-tracking">> = Specific
  const handler = {} as typeof import("../../../app/time-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/timesheets">> = Specific
  const handler = {} as typeof import("../../../app/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/training/catalog/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/catalog/[id]">> = Specific
  const handler = {} as typeof import("../../../app/training/catalog/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/training/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/catalog">> = Specific
  const handler = {} as typeof import("../../../app/training/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/training/my-learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/my-learning">> = Specific
  const handler = {} as typeof import("../../../app/training/my-learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training">> = Specific
  const handler = {} as typeof import("../../../app/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/travel/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel/[id]">> = Specific
  const handler = {} as typeof import("../../../app/travel/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/travel/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel/new">> = Specific
  const handler = {} as typeof import("../../../app/travel/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/travel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel">> = Specific
  const handler = {} as typeof import("../../../app/travel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wellness/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wellness/admin">> = Specific
  const handler = {} as typeof import("../../../app/wellness/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wellness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wellness">> = Specific
  const handler = {} as typeof import("../../../app/wellness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workflows/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/[id]">> = Specific
  const handler = {} as typeof import("../../../app/workflows/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../../app/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/careers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../app/careers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offer-portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/offer-portal">> = Specific
  const handler = {} as typeof import("../../../app/offer-portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign">> = Specific
  const handler = {} as typeof import("../../../app/sign/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
