export const ROLE_CODES = {
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  HR_EXECUTIVE: 'HR_EXECUTIVE',
  HR_ADMIN: 'HR_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export const ALLOCATION_SUMMARY_ROLE_ALLOWLIST = new Set<string>([
  ROLE_CODES.EMPLOYEE,
  ROLE_CODES.MANAGER,
  ROLE_CODES.HR_EXECUTIVE,
  ROLE_CODES.HR_ADMIN,
  ROLE_CODES.SUPER_ADMIN,
]);
