package com.nulogic.hrms.dashboard;
import com.nulogic.hrms.dashboard.dto.EmployeeDashboardData;
import com.nulogic.hrms.dashboard.dto.ExecutiveDashboardData;
import com.nulogic.hrms.dashboard.dto.ManagerDashboardResponse;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
public class DashboardService {

    public EmployeeDashboardData getEmployeeDashboard(UUID userId) {
        return EmployeeDashboardData.builder()
                .employeeId(userId.toString())
                .employeeName("Fayaz Deen")
                .designation("Senior Software Engineer")
                .department("Engineering")
                .attendanceSummary(EmployeeDashboardData.AttendanceSummary.builder()
                        .currentMonth(EmployeeDashboardData.AttendanceCurrentMonth.builder()
                                .present(20)
                                .absent(0)
                                .late(1)
                                .onLeave(1)
                                .totalWorkingDays(22)
                                .attendancePercentage(95.5)
                                .averageWorkHours(8.4)
                                .build())
                        .recentHistory(new ArrayList<>())
                        .weeklyTrend(new ArrayList<>())
                        .build())
                .leaveBalances(List.of(
                        EmployeeDashboardData.LeaveBalanceItem.builder()
                                .leaveTypeName("Annual Leave")
                                .totalQuota(21.0)
                                .available(15.0)
                                .used(6.0)
                                .build()
                ))
                .careerProgress(EmployeeDashboardData.CareerProgress.builder()
                        .currentGoals(new ArrayList<>())
                        .recentReviews(new ArrayList<>())
                        .build())
                .upcomingEvents(new ArrayList<>())
                .stats(EmployeeDashboardData.Stats.builder()
                        .totalLeavesTaken(6)
                        .totalLeavesRemaining(15)
                        .pendingLeaveRequests(0)
                        .build())
                .build();
    }

    public ManagerDashboardResponse getManagerDashboard(UUID userId) {
        return ManagerDashboardResponse.builder()
                .managerId(userId.toString())
                .managerName("Fayaz Deen")
                .departmentName("Engineering")
                .teamOverview(ManagerDashboardResponse.TeamOverview.builder()
                        .directReports(8)
                        .totalTeamSize(12)
                        .activeMembers(11)
                        .onLeave(1)
                        .teamHealthScore(88)
                        .teamHealthStatus("GOOD")
                        .build())
                .teamAttendance(ManagerDashboardResponse.TeamAttendance.builder()
                        .presentToday(7)
                        .absentToday(0)
                        .onLeaveToday(1)
                        .weeklyAttendanceRate(94.0)
                        .build())
                .teamLeave(ManagerDashboardResponse.TeamLeave.builder()
                        .pendingApprovals(2)
                        .onLeaveToday(1)
                        .build())
                .teamPerformance(ManagerDashboardResponse.TeamPerformance.builder()
                        .avgPerformanceRating(4.2)
                        .goalCompletionRate(85.0)
                        .build())
                .actionItems(ManagerDashboardResponse.ActionItems.builder()
                        .leaveApprovals(2)
                        .totalActionItems(2)
                        .build())
                .teamMembers(new ArrayList<>())
                .teamAlerts(new ArrayList<>())
                .build();
    }

    public ExecutiveDashboardData getExecutiveDashboard(UUID userId) {
        return ExecutiveDashboardData.builder()
                .keyMetrics(List.of(
                        ExecutiveDashboardData.KpiCard.builder()
                                .name("Total Headcount")
                                .value("125")
                                .unit("#")
                                .trend("UP")
                                .changePercent(2.4)
                                .changeDescription("vs last month")
                                .status("GOOD")
                                .icon("users")
                                .build(),
                        ExecutiveDashboardData.KpiCard.builder()
                                .name("Monthly Payroll")
                                .value("4.5M")
                                .unit("₹")
                                .trend("UP")
                                .changePercent(1.2)
                                .changeDescription("vs last month")
                                .status("GOOD")
                                .icon("dollar")
                                .build(),
                        ExecutiveDashboardData.KpiCard.builder()
                                .name("Retention Rate")
                                .value("96")
                                .unit("%")
                                .trend("STABLE")
                                .changePercent(0.0)
                                .changeDescription("steady")
                                .status("GOOD")
                                .icon("trending")
                                .build(),
                        ExecutiveDashboardData.KpiCard.builder()
                                .name("Open Positions")
                                .value("8")
                                .unit("#")
                                .trend("DOWN")
                                .changePercent(-12.0)
                                .changeDescription("vs last month")
                                .status("GOOD")
                                .icon("target")
                                .build()
                ))
                .financialSummary(ExecutiveDashboardData.FinancialSummary.builder()
                        .monthlyPayrollCost(4500000.0)
                        .yearToDatePayrollCost(54000000.0)
                        .projectedAnnualPayrollCost(55000000.0)
                        .payrollCostChangePercent(1.2)
                        .avgCostPerEmployee(36000.0)
                        .budgetAllocated(60000000.0)
                        .budgetUtilized(54000000.0)
                        .budgetUtilizationPercent(90.0)
                        .revenuePerEmployee(150000.0)
                        .build())
                .workforceSummary(ExecutiveDashboardData.WorkforceSummary.builder()
                        .totalHeadcount(125)
                        .activeEmployees(118)
                        .contractorCount(7)
                        .openPositions(8)
                        .newHiresThisMonth(4)
                        .terminationsThisMonth(1)
                        .attritionRate(0.8)
                        .retentionRate(96.5)
                        .byDepartment(List.of(
                                ExecutiveDashboardData.DemographicBreakdown.builder().category("Engineering").count(45).percentage(36.0).build(),
                                ExecutiveDashboardData.DemographicBreakdown.builder().category("Sales").count(30).percentage(24.0).build(),
                                ExecutiveDashboardData.DemographicBreakdown.builder().category("Marketing").count(20).percentage(16.0).build(),
                                ExecutiveDashboardData.DemographicBreakdown.builder().category("HR").count(10).percentage(8.0).build(),
                                ExecutiveDashboardData.DemographicBreakdown.builder().category("Finance").count(20).percentage(16.0).build()
                        ))
                        .byLocation(new ArrayList<>())
                        .byEmploymentType(new ArrayList<>())
                        .build())
                .productivityMetrics(ExecutiveDashboardData.ProductivityMetrics.builder()
                        .avgAttendanceRate(94.5)
                        .avgWorkingHours(8.2)
                        .avgPerformanceRating(4.1)
                        .engagementScore(82.0)
                        .eNPS(45)
                        .absenteeismRate(2.5)
                        .highPerformersCount(15)
                        .lowPerformersCount(2)
                        .performanceImprovementRate(4.8)
                        .engagementChangePercent(1.2)
                        .trainingHoursPerEmployee(2.4)
                        .trainingCompletionRate(88.0)
                        .certificationCount(12)
                        .goalCompletionRate(85.0)
                        .goalsOnTrack(10)
                        .goalsAtRisk(2)
                        .goalsDelayed(0)
                        .build())
                .riskIndicators(ExecutiveDashboardData.RiskIndicators.builder()
                        .highRiskEmployees(3)
                        .criticalRiskEmployees(1)
                        .predictedAttritionRate(2.5)
                        .complianceIssuesCount(0)
                        .totalSkillGaps(15)
                        .departmentRisks(new ArrayList<>())
                        .overdueTrainings(5)
                        .expiredCertifications(2)
                        .criticalSkillGaps(3)
                        .skillCoveragePercent(85.0)
                        .keyPositionsWithoutSuccessor(2)
                        .successionReadyPercentage(75.0)
                        .employeesWithHighWorkload(8)
                        .employeesWithExcessiveOvertime(4)
                        .avgOvertimeHours(2.5)
                        .build())
                .trendCharts(ExecutiveDashboardData.TrendCharts.builder()
                        .headcountTrend(List.of(
                                ExecutiveDashboardData.TrendPoint.builder().period("Aug").value(115.0).build(),
                                ExecutiveDashboardData.TrendPoint.builder().period("Sep").value(118.0).build(),
                                ExecutiveDashboardData.TrendPoint.builder().period("Oct").value(120.0).build(),
                                ExecutiveDashboardData.TrendPoint.builder().period("Nov").value(122.0).build(),
                                ExecutiveDashboardData.TrendPoint.builder().period("Dec").value(125.0).build()
                        ))
                        .payrollCostTrend(new ArrayList<>())
                        .attritionTrend(new ArrayList<>())
                        .engagementTrend(new ArrayList<>())
                        .hiringVsAttrition(new ArrayList<>())
                        .build())
                .strategicAlerts(List.of(
                        ExecutiveDashboardData.StrategicAlert.builder()
                                .id("1")
                                .severity("WARNING")
                                .category("ATTRITION")
                                .title("Increasing attrition in Sales")
                                .description("Sales department has seen 3 exits in the last quarter.")
                                .recommendation("Review incentive structure and conduct stay interviews.")
                                .impact("MEDIUM")
                                .trend("WORSENING")
                                .createdAt("2026-01-01T10:00:00Z")
                                .build()
                ))
                .build();
    }
}
