ALTER TABLE compliance_audit_logs
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS performed_by_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS ip_address VARCHAR(255),
  ADD COLUMN IF NOT EXISTS user_agent VARCHAR(255);

ALTER TABLE compliance_checklists
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS next_due_date DATE,
  ADD COLUMN IF NOT EXISTS last_completed_date DATE,
  ADD COLUMN IF NOT EXISTS total_items INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_items INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS assigned_to UUID,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE compliance_policies
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS effective_date DATE,
  ADD COLUMN IF NOT EXISTS expiry_date DATE,
  ADD COLUMN IF NOT EXISTS document_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS requires_acknowledgment BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS acknowledgment_frequency_days INTEGER DEFAULT 365,
  ADD COLUMN IF NOT EXISTS approved_by UUID,
  ADD COLUMN IF NOT EXISTS approved_at DATE,
  ADD COLUMN IF NOT EXISTS policy_version INTEGER DEFAULT 1;
