ALTER TABLE custom_field_definitions
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS min_value DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS max_value DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS min_length INTEGER,
  ADD COLUMN IF NOT EXISTS max_length INTEGER,
  ADD COLUMN IF NOT EXISTS max_file_size BIGINT;

ALTER TABLE custom_field_values
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS date_value DATE,
  ADD COLUMN IF NOT EXISTS date_time_value TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS boolean_value BOOLEAN,
  ADD COLUMN IF NOT EXISTS file_size BIGINT;
