ALTER TABLE document_requests
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS addressed_to VARCHAR(255),
  ADD COLUMN IF NOT EXISTS required_by_date DATE,
  ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(255),
  ADD COLUMN IF NOT EXISTS processed_by UUID,
  ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS generated_document_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS document_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 2;
