-- Align multi-channel notifications with MultiChannelNotification entity fields.

ALTER TABLE multi_channel_notifications
  ADD COLUMN IF NOT EXISTS template_code VARCHAR(255),
  ADD COLUMN IF NOT EXISTS recipient_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS recipient_phone VARCHAR(255),
  ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS title VARCHAR(255),
  ADD COLUMN IF NOT EXISTS action_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS icon VARCHAR(255),
  ADD COLUMN IF NOT EXISTS reference_type VARCHAR(255),
  ADD COLUMN IF NOT EXISTS reference_id UUID,
  ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS retry_count INTEGER,
  ADD COLUMN IF NOT EXISTS last_retry_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS error_message VARCHAR(255),
  ADD COLUMN IF NOT EXISTS external_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS group_key VARCHAR(255),
  ADD COLUMN IF NOT EXISTS is_group_summary BOOLEAN,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
