-- Align survey aggregate tables with their JPA entity mappings.
ALTER TABLE survey_answers
  ADD COLUMN IF NOT EXISTS selected_option INTEGER,
  ADD COLUMN IF NOT EXISTS selected_options VARCHAR(255),
  ADD COLUMN IF NOT EXISTS numeric_answer DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS rating_answer INTEGER,
  ADD COLUMN IF NOT EXISTS ranking VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nps_score INTEGER,
  ADD COLUMN IF NOT EXISTS sentiment_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS key_phrases VARCHAR(255),
  ADD COLUMN IF NOT EXISTS topics VARCHAR(255),
  ADD COLUMN IF NOT EXISTS weighted_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS seconds_spent INTEGER,
  ADD COLUMN IF NOT EXISTS answered_at TIMESTAMPTZ;

ALTER TABLE survey_insights
  ADD COLUMN IF NOT EXISTS department_id UUID,
  ADD COLUMN IF NOT EXISTS location_id UUID,
  ADD COLUMN IF NOT EXISTS impact_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS confidence_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS affected_employees INTEGER,
  ADD COLUMN IF NOT EXISTS percentage_change DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS key_themes VARCHAR(255),
  ADD COLUMN IF NOT EXISTS related_questions VARCHAR(255),
  ADD COLUMN IF NOT EXISTS trend_period_weeks INTEGER,
  ADD COLUMN IF NOT EXISTS assigned_to UUID,
  ADD COLUMN IF NOT EXISTS action_due_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS action_notes VARCHAR(255),
  ADD COLUMN IF NOT EXISTS is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS acknowledged_by UUID,
  ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ;

ALTER TABLE survey_questions
  ADD COLUMN IF NOT EXISTS min_scale INTEGER,
  ADD COLUMN IF NOT EXISTS max_scale INTEGER,
  ADD COLUMN IF NOT EXISTS min_label VARCHAR(255),
  ADD COLUMN IF NOT EXISTS max_label VARCHAR(255),
  ADD COLUMN IF NOT EXISTS weight DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS depends_on_question_id UUID,
  ADD COLUMN IF NOT EXISTS depends_on_answer VARCHAR(255);

ALTER TABLE survey_responses
  ADD COLUMN IF NOT EXISTS employee_id UUID,
  ADD COLUMN IF NOT EXISTS anonymous_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completion_time_minutes INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagement_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS sentiment_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS nps_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS department VARCHAR(255),
  ADD COLUMN IF NOT EXISTS location VARCHAR(255),
  ADD COLUMN IF NOT EXISTS grade VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tenure_months INTEGER,
  ADD COLUMN IF NOT EXISTS ip_address VARCHAR(255),
  ADD COLUMN IF NOT EXISTS user_agent VARCHAR(255);
