apiVersion: v1
kind: Service
metadata:
  name: hrms-frontend
  namespace: hrms
  labels:
    app: hrms
    component: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: hrms
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
