// Compliance Types

export type PolicyCategory =
  | 'EMPLOYMENT'
  | 'SAFETY'
  | 'ANTI_HARASSMENT'
  | 'DATA_PRIVACY'
  | 'CODE_OF_CONDUCT'
  | 'LEAVE'
  | 'TRAVEL'
  | 'EXPENSE'
  | 'IT_SECURITY'
  | 'CONFIDENTIALITY'
  | 'REMOTE_WORK'
  | 'HEALTH'
  | 'ENVIRONMENT'
  | 'CUSTOM';

export type PolicyStatus =
  | 'DRAFT'
  | 'PENDING_APPROVAL'
  | 'APPROVED'
  | 'PUBLISHED'
  | 'ARCHIVED';

export type ChecklistCategory =
  | 'ONBOARDING'
  | 'OFFBOARDING'
  | 'QUARTERLY_REVIEW'
  | 'ANNUAL_AUDIT'
  | 'SAFETY'
  | 'DATA_PRIVACY'
  | 'TRAINING'
  | 'DOCUMENTATION'
  | 'REGULATORY'
  | 'CUSTOM';

export type ChecklistFrequency =
  | 'ONE_TIME'
  | 'WEEKLY'
  | 'MONTHLY'
  | 'QUARTERLY'
  | 'SEMI_ANNUAL'
  | 'ANNUAL';

export type ChecklistStatus =
  | 'NOT_STARTED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'OVERDUE'
  | 'CANCELLED';

export type AuditAction =
  | 'CREATE'
  | 'READ'
  | 'UPDATE'
  | 'DELETE'
  | 'LOGIN'
  | 'LOGOUT'
  | 'LOGIN_FAILED'
  | 'PASSWORD_CHANGE'
  | 'PASSWORD_RESET'
  | 'PERMISSION_CHANGE'
  | 'EXPORT'
  | 'IMPORT'
  | 'APPROVE'
  | 'REJECT'
  | 'SUBMIT'
  | 'CANCEL'
  | 'ARCHIVE'
  | 'RESTORE';

export type AuditSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type AlertType =
  | 'POLICY_EXPIRY'
  | 'LICENSE_RENEWAL'
  | 'TRAINING_DUE'
  | 'ACKNOWLEDGMENT_PENDING'
  | 'DOCUMENT_EXPIRY'
  | 'CHECKLIST_OVERDUE'
  | 'REGULATORY_DEADLINE'
  | 'AUDIT_FINDING'
  | 'CUSTOM';

export type AlertPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type AlertStatus =
  | 'OPEN'
  | 'IN_PROGRESS'
  | 'RESOLVED'
  | 'DISMISSED'
  | 'ESCALATED';

export interface CompliancePolicy {
  id: string;
  tenantId?: string;
  name: string;
  code: string;
  description?: string;
  category: PolicyCategory;
  status: PolicyStatus;
  effectiveDate?: string; // YYYY-MM-DD
  expiryDate?: string; // YYYY-MM-DD
  policyContent?: string;
  documentUrl?: string;
  requiresAcknowledgment?: boolean;
  acknowledgmentFrequencyDays?: number;
  createdBy?: string;
  approvedBy?: string;
  approvedAt?: string; // YYYY-MM-DD
  policyVersion?: number;
  createdAt?: string; // ISO 8601 DateTime
  updatedAt?: string; // ISO 8601 DateTime
  lastModifiedBy?: string;
  version?: number;
}

export interface PolicyAcknowledgment {
  id: string;
  tenantId?: string;
  policyId: string;
  employeeId: string;
  policyVersion: number;
  acknowledgedAt?: string; // ISO 8601 DateTime
  ipAddress?: string;
  userAgent?: string;
  digitalSignature?: string;
  createdAt?: string; // ISO 8601 DateTime
  updatedAt?: string; // ISO 8601 DateTime
  createdBy?: string;
  lastModifiedBy?: string;
  version?: number;
}

export interface ComplianceChecklist {
  id: string;
  tenantId?: string;
  name: string;
  description?: string;
  category: ChecklistCategory;
  frequency: ChecklistFrequency;
  nextDueDate?: string; // YYYY-MM-DD
  lastCompletedDate?: string; // YYYY-MM-DD
  totalItems?: number;
  completedItems?: number;
  assignedTo?: string;
  status: ChecklistStatus;
  isActive?: boolean;
  createdAt?: string; // ISO 8601 DateTime
  updatedAt?: string; // ISO 8601 DateTime
  createdBy?: string;
  lastModifiedBy?: string;
  version?: number;
}

export interface AuditLog {
  id: string;
  tenantId?: string;
  action: AuditAction;
  entityType: string;
  entityId?: string;
  entityName?: string;
  performedBy: string;
  performedByName?: string;
  timestamp: string; // ISO 8601 DateTime
  oldValue?: string;
  newValue?: string;
  changedFields?: string;
  ipAddress?: string;
  userAgent?: string;
  additionalInfo?: string;
  severity?: AuditSeverity;
  createdAt?: string; // ISO 8601 DateTime
  updatedAt?: string; // ISO 8601 DateTime
  createdBy?: string;
  lastModifiedBy?: string;
  version?: number;
}

export interface ComplianceAlert {
  id: string;
  tenantId?: string;
  title: string;
  description?: string;
  type: AlertType;
  priority: AlertPriority;
  status: AlertStatus;
  dueDate?: string; // YYYY-MM-DD
  relatedEntityId?: string;
  relatedEntityType?: string;
  assignedTo?: string;
  resolvedBy?: string;
  resolvedAt?: string; // ISO 8601 DateTime
  resolutionNotes?: string;
  isAutoGenerated?: boolean;
  reminderCount?: number;
  lastReminderSent?: string; // ISO 8601 DateTime
  createdAt?: string; // ISO 8601 DateTime
  updatedAt?: string; // ISO 8601 DateTime
  createdBy?: string;
  lastModifiedBy?: string;
  version?: number;
}

export interface PolicyAcknowledgmentRequest {
  signature?: string;
  ipAddress?: string;
}

export interface ComplianceAlertStatusRequest {
  status: AlertStatus;
  resolution?: string;
}

export interface ComplianceAlertAssignRequest {
  assigneeId: string;
}

export interface Page<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
}
