package com.nulogic.domain.compliance;

import com.nulogic.common.entity.TenantAware;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.SQLRestriction;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

@SQLRestriction("is_deleted = false")
@Entity
@Table(name = "compliance_alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
public class ComplianceAlert extends TenantAware {


    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertPriority priority;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private AlertStatus status = AlertStatus.OPEN;

    private LocalDate dueDate;

    private UUID relatedEntityId;
    private String relatedEntityType;

    private UUID assignedTo;

    private UUID resolvedBy;
    private LocalDateTime resolvedAt;
    private String resolutionNotes;

    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Builder.Default
    private Integer reminderCount = 0;

    private LocalDateTime lastReminderSent;

    public void resolve(UUID resolvedById, String notes) {
        this.status = AlertStatus.RESOLVED;
        this.resolvedBy = resolvedById;
        this.resolvedAt = LocalDateTime.now(); // JVM-local: entity-layer; push to service per docs/architecture/tenant-time-wave-13-summary.md if cross-region zone correctness is needed
        this.resolutionNotes = notes;
    }

    public void escalate() {
        this.status = AlertStatus.ESCALATED;
    }

    public enum AlertType {
        POLICY_EXPIRY,
        LICENSE_RENEWAL,
        TRAINING_DUE,
        ACKNOWLEDGMENT_PENDING,
        DOCUMENT_EXPIRY,
        CHECKLIST_OVERDUE,
        REGULATORY_DEADLINE,
        AUDIT_FINDING,
        CUSTOM
    }

    public enum AlertPriority {
        LOW,
        MEDIUM,
        HIGH,
        CRITICAL
    }

    public enum AlertStatus {
        OPEN,
        IN_PROGRESS,
        RESOLVED,
        DISMISSED,
        ESCALATED
    }
}
